### ISSUE TITLE
Figlet() - Can't get rid of starting tab!

### ISSUE THREAD

**Issue by strln0750** [laminas/laminas-text#11]
Hey Devs!

I finally was able to get Laminas\Text\Figlet() working and I've wrapped it in a `<pre></pre>`
it's rendering great, and I can supply different .flf files to change the font and everything. 

But for whatever reason it appears that there is a starting TAB or two in the rendered text, the second line on down is fine. It's just that starting line which seems to be indented.

Am I encasing it improperly? Or are there any other tricks I should be observing when embedding this into HTML to keep the formatting correct?

Attached is a screenshot of the artifact:
![laminas](https://user-images.githubusercontent.com/71884983/182924472-f6022438-0bd4-44b5-8762-783fbe937cdf.png)

Thanks!

**Comment by froschdesign** [comment]
@strln0750 
Please also add the text output here.
Thanks in advance! 👍🏻

**Comment by strln0750** [comment]
> @strln0750 Please also add the text output here. Thanks in advance! 👍🏻

Hey Frosch, I was the guy on the Laminas Forums asking about Laminas\Figlet as well. I didn't want to clog it up with my newbie HTML issues. 

And you know what, embarrassingly, I found the problem, I think I have a misunderstanding of white space, tabs and such in my editor, so the `<pre>` tag was inserting a TAB I was unaware of. I use a lot of tabs for case, and I think this is a bad habit I picked up. 
 
```
<pre class="laminas-test">
        <?php
          require __DIR__ . '/vendor/autoload.php';
          use Laminas\Text\Figlet;
	  $configArray = [
            'justification'  => 'JUSTIFICATION_CENTER',
            'outputWidth' => '120',
            	];
          $figlet = new Laminas\Text\Figlet\Figlet($configArray);
          echo $figlet->render('LAMINAS');
        ?>
      </pre>
```

Thank you for looking!
